---
- name: Deploy "{{ name }}"
  proxmox_kvm:
    api_user    : "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host    : "{{ api_host }}"
    node        : "{{ node }}"
    name        : "{{ name }}"
    state: started

- name: Get "{{ name }}" VMID
  proxmox_kvm:
    api_user    : "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host    : "{{ api_host }}"
    node        : "{{ node }}"
    name        : "{{ name }}"
    state: current
  register: result

- name: Set "{{ name }}" VMID
  set_fact:
    vmid: "{{ result.msg | regex_replace('^.* = (\\d+).*?$', '\\1') }}"

- name: Waiting install finish - "{{ name }}"
  pause:
    seconds: 600

- name: Stop "{{ name }}"
  proxmox_kvm:
    api_user    : "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host    : "{{ api_host }}"
    node        : "{{ node }}"
    name        : "{{ name }}"
    state       : stopped
    force       : yes

- name: Waiting stop finish - "{{ name }}"
  pause:
    seconds: 30

- name: Remove deploy args from "{{ name }}"
  proxmox_kvm:
    api_user    : "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host    : "{{ api_host }}"
    node        : "{{ node }}"
    name        : "{{ name }}"
    delete: args

- name: Start "{{ name }}"
  proxmox_kvm:
    api_user    : "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host    : "{{ api_host }}"
    node        : "{{ node }}"
    name        : "{{ name }}"
    state: started
...
